version: '3'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-password}
      - FASTAPI_BASE_URL=http://host.docker.internal:8000 # For connecting to FastAPI running on host
      - NOTIFICATION_SERVICE_URL=http://host.docker.internal:8000/api
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - workflow-network

  # Optional Redis instance for workflow data persistence
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - workflow-network

networks:
  workflow-network:
    driver: bridge 